///$tab Variable
Set vSortBy = 7;
Set vCurrency = 'UZS';
Set vRevaluation = 'Переоценка';
Set vConstructor = WildMatch('|'&Concat(_Конструктор_Num,'|')&'|','*|$1|*')=1;
Set vConstructor_Measures = WildMatch('|'&Concat(_Конструктор_mea_Num,'|')&'|','*|$1|*')=1;
Set vАЕИ = 1;

Set HidePrefix = '_';


Let vThisYear = Year(Today());
Let vThisMonth = Month(Today());
Let vPrevMonth = Month(AddMonths(Today(),-1));